name: Napi piaci elemzés

on:
  schedule:
    - cron: "0 7 * * *"   # minden nap 7:00 (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python futtatás
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Script futtatása
        run: python main.py
